// Auto-generated by the ops app's showroom sync — do not edit by hand.
// Reflects real Turso inventory as of the timestamp below.
window.LIVE_INVENTORY = {
  "120": {
    "white": {
      "left": 0,
      "right": 0,
      "middle": 0,
      "ottoman": 0,
      "wedge": 0
    },
    "black": {
      "left": 0,
      "right": 0,
      "middle": 0,
      "ottoman": 1,
      "wedge": 0
    },
    "beige": {
      "left": 1,
      "right": 1,
      "middle": 1,
      "ottoman": 1,
      "wedge": 1
    },
    "orange": {
      "left": 0,
      "right": 0,
      "middle": 0,
      "ottoman": 0,
      "wedge": 0
    }
  },
  "121": {
    "white": {
      "corner": 6,
      "middle": 2,
      "ottoman": 2
    },
    "black": {
      "corner": 4,
      "middle": 9,
      "ottoman": 2
    },
    "grey": {
      "corner": 2,
      "middle": 0,
      "ottoman": 2
    },
    "khaki": {
      "corner": 4,
      "middle": 1,
      "ottoman": 0
    }
  },
  "140": {
    "black": {
      "left": 2,
      "right": 3,
      "middle": 5,
      "ottoman": 4,
      "wedge": 1
    },
    "grey": {
      "left": 0,
      "right": 1,
      "middle": 1,
      "ottoman": 1,
      "wedge": 0
    },
    "white": {
      "left": 0,
      "right": 0,
      "middle": 1,
      "ottoman": 0,
      "wedge": 0
    },
    "khaki": {
      "left": 0,
      "right": 3,
      "middle": 2,
      "ottoman": 1,
      "wedge": 1
    }
  },
  "141": {
    "black": {
      "corner": 0,
      "middle": 1,
      "ottoman": 0
    },
    "grey": {
      "corner": 3,
      "middle": 2,
      "ottoman": 1
    },
    "beige": {
      "corner": 0,
      "middle": 2,
      "ottoman": 0
    },
    "tan": {
      "corner": 2,
      "middle": 2,
      "ottoman": 0
    }
  },
  "142": {
    "grey": {
      "corner": 0,
      "middle": 0,
      "ottoman": 0
    },
    "black": {
      "corner": 3,
      "middle": 2,
      "ottoman": 1
    },
    "beige": {
      "corner": 0,
      "middle": 1,
      "ottoman": 0
    },
    "khaki": {
      "corner": 0,
      "middle": 0,
      "ottoman": 1
    }
  }
};
// Per-line config piece requirements, derived from PRESET_SEEDS. Every
// showroom page (home + product pages) reads these instead of hardcoding
// its own copy, so a preset change here propagates everywhere on next sync.
window.LIVE_CONFIG_REQUIREMENTS = {
  "120": {
    "Big U": {
      "left": 1,
      "right": 1,
      "middle": 2,
      "ottoman": 2
    },
    "Small L": {
      "left": 1,
      "right": 1,
      "middle": 1,
      "ottoman": 1,
      "wedge": 1
    }
  },
  "121": {
    "Standard L with Ottoman": {
      "corner": 3,
      "middle": 2,
      "ottoman": 1
    },
    "L with double ottoman": {
      "corner": 3,
      "middle": 2,
      "ottoman": 2
    },
    "L": {
      "corner": 3,
      "middle": 2,
      "ottoman": 0
    },
    "Small U": {
      "corner": 2,
      "middle": 3,
      "ottoman": 1
    },
    "Big U": {
      "corner": 2,
      "middle": 2,
      "ottoman": 2
    },
    "Ultra": {
      "corner": 2,
      "middle": 4,
      "ottoman": 2
    }
  },
  "140": {
    "Standard L": {
      "left": 1,
      "right": 1,
      "middle": 2,
      "ottoman": 1,
      "wedge": 1
    },
    "L": {
      "left": 1,
      "right": 1,
      "middle": 2,
      "ottoman": 0,
      "wedge": 1
    },
    "Big U": {
      "left": 1,
      "right": 1,
      "middle": 2,
      "ottoman": 2
    },
    "Small L": {
      "left": 1,
      "right": 1,
      "middle": 1,
      "ottoman": 1,
      "wedge": 1
    }
  },
  "141": {
    "Standard L with Ottoman": {
      "corner": 3,
      "middle": 2,
      "ottoman": 1
    },
    "3 Seater with double ottoman": {
      "corner": 3,
      "middle": 2,
      "ottoman": 2
    },
    "L": {
      "corner": 3,
      "middle": 2,
      "ottoman": 0
    },
    "Small U": {
      "corner": 2,
      "middle": 3,
      "ottoman": 1
    },
    "Big U": {
      "corner": 2,
      "middle": 2,
      "ottoman": 2
    },
    "Ultra": {
      "corner": 2,
      "middle": 4,
      "ottoman": 2
    }
  },
  "142": {
    "Standard L with Ottoman": {
      "corner": 3,
      "middle": 2,
      "ottoman": 1
    }
  }
};
window.LIVE_INVENTORY_SYNCED_AT = "2026-07-11T20:21:30.323Z";
