// Auto-generated by the ops app's showroom sync — do not edit by hand.
// Reflects real Turso inventory as of the timestamp below.
window.LIVE_INVENTORY = {
  "120": {
    "white": {
      "left": 0,
      "right": 0,
      "middle": 0,
      "ottoman": 0,
      "wedge": 0
    },
    "black": {
      "left": 0,
      "right": 0,
      "middle": 0,
      "ottoman": 0,
      "wedge": 0
    },
    "beige": {
      "left": 1,
      "right": 1,
      "middle": 1,
      "ottoman": 2,
      "wedge": 1
    },
    "orange": {
      "left": 0,
      "right": 0,
      "middle": 0,
      "ottoman": 0,
      "wedge": 0
    }
  },
  "121": {
    "white": {
      "corner": 6,
      "middle": 2,
      "ottoman": 2
    },
    "black": {
      "corner": 4,
      "middle": 9,
      "ottoman": 2
    },
    "grey": {
      "corner": 2,
      "middle": 0,
      "ottoman": 2
    },
    "khaki": {
      "corner": 4,
      "middle": 1,
      "ottoman": 0
    }
  },
  "140": {
    "black": {
      "left": 2,
      "right": 3,
      "middle": 5,
      "ottoman": 4,
      "wedge": 1
    },
    "grey": {
      "left": 0,
      "right": 1,
      "middle": 1,
      "ottoman": 1,
      "wedge": 0
    },
    "white": {
      "left": 0,
      "right": 0,
      "middle": 1,
      "ottoman": 0,
      "wedge": 0
    },
    "khaki": {
      "left": 0,
      "right": 3,
      "middle": 2,
      "ottoman": 1,
      "wedge": 1
    }
  },
  "141": {
    "black": {
      "corner": 0,
      "middle": 1,
      "ottoman": 0
    },
    "grey": {
      "corner": 3,
      "middle": 2,
      "ottoman": 1
    },
    "beige": {
      "corner": 0,
      "middle": 2,
      "ottoman": 0
    },
    "tan": {
      "corner": 2,
      "middle": 2,
      "ottoman": 0
    }
  },
  "142": {
    "grey": {
      "corner": 0,
      "middle": 0,
      "ottoman": 0
    },
    "black": {
      "corner": 3,
      "middle": 2,
      "ottoman": 1
    },
    "beige": {
      "corner": 0,
      "middle": 1,
      "ottoman": 0
    },
    "khaki": {
      "corner": 0,
      "middle": 0,
      "ottoman": 1
    }
  }
};
window.LIVE_INVENTORY_SYNCED_AT = "2026-07-09T21:26:52.248Z";
