// Auto-generated by the ops app's showroom sync — do not edit by hand.
// Reflects real Turso inventory as of the last successful sync. If this file
// is missing or fails to load, every showroom page falls back to its own
// last-known-good numbers, so a sync outage never breaks the site.
window.LIVE_INVENTORY = {};
window.LIVE_INVENTORY_SYNCED_AT = null;
